[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["ASOsipov7493 <stokesqwerty@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
